name: gesi_mobile
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"
dependencies:
  animations: ^2.0.2
  badges: ^3.1.2
  change_app_package_name: ^1.0.0
  cupertino_icons: ^1.0.2
  dart_amqp: ^0.2.1
  dio: ^5.3.3
  extended_image: ^8.1.1
  fl_chart: ^0.45.0
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.7
  get: ^4.6.5
  google_fonts: ^6.1.0
  hive: ^2.0.5
  hive_flutter: null
  material_design_icons_flutter: ^5.0.6595
  palette_generator: ^0.3.3
  persistent_bottom_nav_bar: ^5.0.2
  flutter_expandable_fab: ^2.0.0
  salomon_bottom_bar: ^3.2.0
  flutter_dotenv: ^5.1.0
  syncfusion_flutter_calendar: ^23.1.40
  flutter_staggered_animations: ^1.1.1
  web_socket_channel: ^2.1.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  glass_kit: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/courses/
    - .env
